import './globals.css'

export const metadata = {
  title: 'Sudoku!',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='h-screen bg-sky-50'>
        <main className="h-full bg-background flex items-center">
          {children}
        </main>
      </body>
    </html>
  )
}
