import "./globals.css";
import { Quicksand } from "next/font/google";

export const metadata = {
  title: "Sudoku!",
  description: "Generated by create next app",
};

const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={quicksand.className}>
      <body className="h-screen">
        <main className="h-full bg-background flex items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
